# Docker Compose file for a Baikal server with local mounts instead of Docker volumes

# Before you start docker compose up, make sure that you have prepared
# the local folders to avoid file permission issues with
#
# mkdir -p config Specific/db
# chown -R 101:101 config Specific  <- Use this for Nginx
# chown -R 33:33 config Specific    <- Use this for Apache httpd

version: "2"
services:
  baikal:
    container_name: baikal
    image: ckulka/baikal:nginx
    restart: always
    # ports:
    #   - "80:80"
    volumes:
      - /docker/baikal/config:/var/www/baikal/config
      - /docker/baikal/Specific:/var/www/baikal/Specific
    networks:
      - npm_net

networks:
  npm_net:
    external: true
