# Docker Compose file for a Baikal server with local mounts instead of Docker volumes

# Before you start docker compose up, make sure that you have prepared
# the local folders to avoid file permission issues with
#
# mkdir -p config Specific/db
# chown -R 101:101 config Specific  <- Use this for Nginx
# chown -R 33:33 config Specific    <- Use this for Apache httpd

version: "2"
services:
  baikal:
    container_name: baikal
    image: ckulka/baikal:nginx
    restart: always
    # ports:
    #   - "80:80"
    environment:
      # Configure local network whitelist - space-separated list of IP ranges
      BAIKAL_LOCAL_WHITELIST: "192.168.1.0/24 10.0.0.0/8 172.16.0.0/12 127.0.0.1/32"
    volumes:
      - /docker/baikal/config:/var/www/baikal/config
      - /docker/baikal/Specific:/var/www/baikal/Specific
      # Mount the whitelist-enabled nginx configuration
      - /home/jwowk/repos/baikal-docker/files/nginx-whitelist.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount the plugin installation script
      - /home/jwowk/repos/baikal-docker/files/docker-entrypoint.d/nginx/46-install-whitelist-plugin.sh:/docker-entrypoint.d/46-install-whitelist-plugin.sh:ro
      # Mount the PHP whitelist plugin
      - /home/jwowk/repos/baikal-docker/files/docker-entrypoint.d/LocalNetworkWhitelistPlugin.php:/docker-entrypoint.d/LocalNetworkWhitelistPlugin.php:ro
      # Mount the whitelist auth backend
      - /home/jwowk/repos/baikal-docker/files/docker-entrypoint.d/WhitelistPDOBasicAuth.php:/docker-entrypoint.d/WhitelistPDOBasicAuth.php:ro
    networks:
      - npm_net

networks:
  npm_net:
    external: true



