# Docker Compose file for a Baikal server with local mounts instead of Docker volumes

# Before you start docker compose up, make sure that you have prepared
# the local folders to avoid file permission issues with
#
# mkdir -p config Specific/db
# chown -R 101:101 config Specific  <- Use this for Nginx
# chown -R 33:33 config Specific    <- Use this for Apache httpd

version: "2"
services:
  baikal:
    container_name: baikal
    image: ckulka/baikal:nginx
    restart: always
    # ports:
    #   - "80:80"
        environment:
      # Configure local network whitelist - space-separated list of IP ranges
      # Common private network ranges:
      # - 192.168.0.0/16 (192.168.x.x networks)
      # - 10.0.0.0/8 (10.x.x.x networks)
      # - 172.16.0.0/12 (172.16.x.x to 172.31.x.x networks)
      # - 127.0.0.0/8 (localhost)
      BAIKAL_LOCAL_WHITELIST: "192.168.1.0/24 10.0.0.0/8 172.16.0.0/12 127.0.0.1/32"
    volumes:
      - /docker/baikal/config:/var/www/baikal/config
      - /docker/baikal/Specific:/var/www/baikal/Specific
      # Mount the whitelist-enabled nginx configuration
      - ./files/nginx-whitelist.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount the whitelist injection script
      - ./files/docker-entrypoint.d/nginx/45-inject-whitelist.sh:/docker-entrypoint.d/45-inject-whitelist.sh:ro
      # Mount the PHP whitelist plugin
      - ./files/docker-entrypoint.d/LocalNetworkWhitelistPlugin.php:/docker-entrypoint.d/LocalNetworkWhitelistPlugin.php:ro

    volumes:

    networks:
      - npm_net

networks:
  npm_net:
    external: true


# Docker Compose file for Baikal server with local network whitelist
# This example shows how to configure Baikal to allow local network access without authentication

version: "2"
services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - "80:80"
    environment:
      # Configure local network whitelist - space-separated list of IP ranges
      # Common private network ranges:
      # - 192.168.0.0/16 (192.168.x.x networks)
      # - 10.0.0.0/8 (10.x.x.x networks)
      # - 172.16.0.0/12 (172.16.x.x to 172.31.x.x networks)
      # - 127.0.0.0/8 (localhost)
      BAIKAL_LOCAL_WHITELIST: "192.168.1.0/24 10.0.0.0/8 172.16.0.0/12 127.0.0.1/32"
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific
      # Mount the whitelist-enabled nginx configuration
      - ./files/nginx-whitelist.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount the whitelist injection script
      - ./files/docker-entrypoint.d/nginx/45-inject-whitelist.sh:/docker-entrypoint.d/45-inject-whitelist.sh:ro
      # Mount the PHP whitelist plugin
      - ./files/docker-entrypoint.d/LocalNetworkWhitelistPlugin.php:/docker-entrypoint.d/LocalNetworkWhitelistPlugin.php:ro

volumes:
  config:
  data:
